-- Peak — make modmail message ordering deterministic.
--
-- created_at can tie (same transaction, bulk import), which made "the last
-- message" ambiguous. A monotonic seq fixes ordering for the readers.

alter table modmail_message add column seq bigint generated by default as identity;
create index modmail_message_seq on modmail_message (thread_id, seq);

-- ── readers re-pinned to seq ──────────────────────────────────────────
create or replace function my_modmail_threads()
returns table (
  id uuid, community_id uuid, community_slug citext, community_name text,
  subject text, state modmail_state, created_at timestamptz,
  last_message_at timestamptz, message_count int,
  last_snippet text, last_from_mod boolean
)
language sql stable security definer set search_path = public as $$
  select
    t.id, t.community_id, c.slug, c.name,
    t.subject, t.state, t.created_at, t.last_message_at,
    (select count(*)::int from modmail_message m where m.thread_id = t.id),
    (select left(m.body, 140) from modmail_message m
     where m.thread_id = t.id order by m.seq desc limit 1),
    (select m.from_mod from modmail_message m
     where m.thread_id = t.id order by m.seq desc limit 1)
  from modmail_thread t
  join community c on c.id = t.community_id
  where t.member_id = auth.uid()
  order by t.last_message_at desc;
$$;

create or replace function community_modmail_threads(
  p_community_id uuid, p_state text default 'open'
)
returns table (
  id uuid, subject text, state modmail_state,
  created_at timestamptz, last_message_at timestamptz, message_count int,
  last_snippet text, last_from_mod boolean,
  member_id uuid, member_handle citext, member_domain text,
  member_display_name text, member_avatar_path text,
  member_state community_member_state
)
language sql stable security definer set search_path = public as $$
  select
    t.id, t.subject, t.state, t.created_at, t.last_message_at,
    (select count(*)::int from modmail_message m where m.thread_id = t.id),
    (select left(m.body, 140) from modmail_message m
     where m.thread_id = t.id order by m.seq desc limit 1),
    (select m.from_mod from modmail_message m
     where m.thread_id = t.id order by m.seq desc limit 1),
    p.id, p.handle, p.domain, p.display_name, p.avatar_path,
    (select cm.state from community_member cm
     where cm.community_id = t.community_id and cm.member_id = t.member_id)
  from modmail_thread t
  join profile p on p.id = t.member_id
  where t.community_id = p_community_id
    and community_can_moderate(p_community_id, auth.uid())
    and (p_state = 'all' or t.state::text = p_state)
  order by t.last_message_at desc;
$$;

create or replace function modmail_messages(p_thread_id uuid)
returns table (
  id uuid, sender_id uuid, sender_handle citext, sender_display_name text,
  sender_avatar_path text, from_mod boolean, body text, created_at timestamptz
)
language sql stable security definer set search_path = public as $$
  select
    m.id, m.sender_id, s.handle, s.display_name, s.avatar_path,
    m.from_mod, m.body, m.created_at
  from modmail_message m
  join modmail_thread t on t.id = m.thread_id
  left join profile s on s.id = m.sender_id
  where m.thread_id = p_thread_id
    and (t.member_id = auth.uid()
         or community_can_moderate(t.community_id, auth.uid()))
  order by m.seq;
$$;
